Add date/time to ctest runs
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/branches/Branch-2.2@7047 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/nightly-all b/regress/nightly-all
--- a/regress/nightly-all
+++ b/regress/nightly-all
@@ -3,6 +3,7 @@
 # run both the disk and the tape based regression tests.
 #
 # Include full output
+echo "Begin nightly-all `date`"
 save_debug=${REGRESS_DEBUG}
 REGRESS_DEBUG=1
 export REGRESS_DEBUG
@@ -12,5 +13,12 @@ nice ctest -D Nightly -R "^(disk|tape|changer):"
 if [ $? != 0 ] ; then
    echo "ctest failed re-running Submit"
    ctest -D NightlySubmit
+   if [ $? != 0 ] ; then
+      echo "Submit failed, waiting 5 mins"
+      sleep 300
+      echo "ctest failed re-running Submit a second time"
+      ctest -D NightlySubmit
+   fi
 fi
 REGRESS_DEBUG=${save_debug}
+echo "End nightly-all `date`"
diff --git a/regress/nightly-disk-and-tape b/regress/nightly-disk-and-tape
--- a/regress/nightly-disk-and-tape
+++ b/regress/nightly-disk-and-tape
@@ -3,6 +3,7 @@
 # test only the disk based regression scripts
 #
 # Include full output
+echo "Begin nightly-disk-and-tape `date`"
 save_debug=${REGRESS_DEBUG}
 REGRESS_DEBUG=1
 export REGRESS_DEBUG
@@ -12,5 +13,12 @@ nice ctest -D Experimental -R "^(disk|tape):"
 if [ $? != 0 ] ; then
    echo "ctest failed re-running Submit"
    ctest -D ExperimentalSubmit
+   if [ $? != 0 ] ; then
+      echo "Submit failed, waiting 5 mins"
+      sleep 300
+      echo "ctest failed re-running Submit a second time"
+      ctest -D NightlySubmit
+   fi
 fi
 REGRESS_DEBUG=${save_debug}
+echo "End nightly-disk-and-tape `date`"
